version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: reklem_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - reklem_net

    nginx:
        image: nginx:stable-alpine
        container_name: reklem_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - reklem_net

networks:
    reklem_net:
        driver: bridge
