services:
    - type: web
      name: reklem
      env: docker
      dockerfilePath: ./Dockerfile
      plan: starter
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            sync: false
          - key: DB_CONNECTION
            sync: false
          - key: DB_HOST
            sync: false
          - key: DB_PORT
            sync: false
          - key: DB_DATABASE
            sync: false
          - key: DB_USERNAME
            sync: false
          - key: DB_PASSWORD
            sync: false
      autoDeploy: true
