services:
  - type: web
    name: reklem
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_NAME
        value: Reklem
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:l1ObAYgvG8Ysy5CKTVe/5uN8FFl7+xw8hq9+t0cuyNg=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://reklem.onrender.com
      - key: FRONTEND_URL
        value: https://reklem.onrender.com
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: PHP_CLI_SERVER_WORKERS
        value: 4
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-2.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.mgjyxgaiyngflmlfzoju
      - key: DB_PASSWORD
        value: root
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: log
      - key: MAIL_SCHEME
        value: null
      - key: MAIL_HOST
        value: 127.0.0.1
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Reklem
      - key: VITE_APP_NAME
        value: Reklem
      - key: PORT
        value: 10000 