const productData = {
    1:{title: "Брелок «Alen» круглый",
        price: 81,
        img: ("../src/img/catalog/icon3/1.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    2:{title: "Брелок прямоугольный «Alen 2.0»",
        price: 166,
        img: ("../src/img/catalog/icon3/2.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    3:{title: "Брелок «Mondo»",
        price: 187,
        img: ("../src/img/catalog/icon3/3.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    4:{title: "Брелок-открывалка «Dao»",
        price: 86,
        img: ("../src/img/catalog/icon3/4.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    5:{title: "Антистресс «Кубик»",
        price: 176,
        img: ("../src/img/catalog/icon3/5.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    6:{title: "Антистресс «Каска»",
        price: 69,
        img: ("../src/img/catalog/icon3/6.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    7:{title: "Антистресс «Куб»",
        price: 49,
        img: ("../src/img/catalog/icon3/7.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    8:{title: "Зеркало складное",
        price: 450,
        img: ("../src/img/catalog/icon3/8.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    9:{title: "Брелок «Triangle»",
        price: 90,
        img: ("../src/img/catalog/icon3/9.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    10:{title: "Брелок-рулетка «Домик»",
        price: 90,
        img: ("../src/img/catalog/icon3/10.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    11:{title: "Брелок-рулетка «Block»",
        price: 60,
        img: ("../src/img/catalog/icon3/11.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    12:{title: "Сумка с клапаном",
        price: 500,
        img: ("../src/img/catalog/icon3/12.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    13:{title: "Брелок металл «жетон»",
        price: 65,
        img: ("../src/img/catalog/icon3/13.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    14:{title: "Брелок из нержавеющей стали «круг»",
        price: 30,
        img: ("../src/img/catalog/icon3/14.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    15:{title: "Брелок акрил прямоугольник",
        price: 50,
        img: ("../src/img/catalog/icon3/15.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    16:{title: "Зажигалка  бензиновая",
        price: 250,
        img: ("../src/img/catalog/icon3/16.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
};
