const productData = {
    1:{title: "Алюминиевая шариковая ручка «Joyce»", 
        price: 107, 
        img: ("../src/img/catalog/icon4/1.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    2:{title: "Шариковая ручка «PET PEN PRO»", 
        price: 177, 
        img: ("../src/img/catalog/icon4/2.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    3:{title: "Ручка картонная шариковая «Эко»", 
        price: 30, 
        img: ("../src/img/catalog/icon4/3.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    4:{title: "Ручка soft-touch шариковая «Plane»", 
        price: 40, 
        img: ("../src/img/catalog/icon4/4.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    5:{title: "Ручка soft-touch шариковая «Taper»", 
        price: 50, 
        img: ("../src/img/catalog/icon4/5.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    6:{title: "Ручка soft-touch шариковая «Zorro»", 
        price: 50, 
        img: ("../src/img/catalog/icon4/6.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    7:{title: "Ручка  шариковая «Prodir»", 
        price: 146, 
        img: ("../src/img/catalog/icon4/7.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    8:{title: "Конференц сумка «Session»", 
        price: 686, 
        img: ("../src/img/catalog/icon4/8.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    9:{title: "Конференц сумка для документов «Congress»", 
        price: 667, 
        img: ("../src/img/catalog/icon4/9.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    10:{title: "Конференц сумка для документов «Event»", 
        price: 511, 
        img: ("../src/img/catalog/icon4/10.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    11:{title: "Блокнот «Pocket»", 
        price: 685, 
        img: ("../src/img/catalog/icon4/11.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    12:{title: "Бизнес-блокнот А5 с клапаном «Fabrizio»", 
        price: 1506, 
        img: ("../src/img/catalog/icon4/12.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    13:{title: "Блокнот A6 «Stitch»", 
        price: 112, 
        img: ("../src/img/catalog/icon4/13.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    14:{title: "Блокнот A7 «Rainbow S»", 
        price: 175, 
        img: ("../src/img/catalog/icon4/14.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    15:{title: "Набор стикеров «Expose» с ручкой и блокнотом А7", 
        price: 170, 
        img: ("../src/img/catalog/icon4/15.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
    16:{title: "Блокнот «Priestly» с ручкой", 
        price: 417, 
        img: ("../src/img/catalog/icon4/16.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
     },
};
