const productData = {
    1:{title: "Вакуумная герметичная термокружка «Inter»",
        price: 600,
        img: ("../src/img/catalog/icon2/1.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    2:{title: "Вакуумная термокружка «Sense»",
        price: 700,
        img: ("../src/img/catalog/icon2/2.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    3:{title: "Вакуумная термокружка «Valhalla»",
        price: 700,
        img: ("../src/img/catalog/icon2/3.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    4:{title: "Вакуумная термокружка c кнопкой «Waterline»",
        price: 700,
        img: ("../src/img/catalog/icon2/4.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    5:{title: "Термокружка с медной изоляцией «Waterline»",
        price: 700,
        img: ("../src/img/catalog/icon2/5.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    6:{title: "Вакуумная термокружка с кнопкой «Streamline»",
        price: 700,
        img: ("../src/img/catalog/icon2/6.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    7:{title: "Вакуумная термокружка с кнопкой «Upgrade»",
        price: 700,
        img: ("../src/img/catalog/icon2/7.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    8:{title: "Кружка с термоизоляцией «Silence»",
        price: 700,
        img: ("../src/img/catalog/icon2/8.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    9:{title: "Кружка с термоизоляцией треугольная",
        price: 700,
        img: ("../src/img/catalog/icon2/9.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    10:{title: "Кружка с термоизоляцией  с металлической крышкой",
        price: 700,
        img: ("../src/img/catalog/icon2/10.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    11:{title: "Кружка с термоизоляцией волнистая",
        price: 700,
        img: ("../src/img/catalog/icon2/11.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"},
    12:{title: "Кружка стальная «Alaska» с крышкой слайдером",
        price: 700,
        img: ("../src/img/catalog/icon2/12.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    13:{title: "Пластиковый стакан «Take away»",
        price: 700,
        img: ("../src/img/catalog/icon2/13.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    14:{title: "Стакан-тамблер «Moment» с кофейной крышкой",
        price: 700,
        img: ("../src/img/catalog/icon2/14.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    15:{title: "Термокружка «Jar»",
        price: 700,
        img: ("../src/img/catalog/icon2/15.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
    16:{title: "Термокружка «Klein» ",
        price: 700,
        img: ("../src/img/catalog/icon2/16.svg"),
        description:"",
        quantity: 27,
        art:"Арт. 1356.60.2"
    },
};
